name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Copy JAR to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ec2-user
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 400 key.pem
          echo "Host: $EC2_HOST"  # Debug step
          scp -o StrictHostKeyChecking=no -i key.pem target/policysync-0.0.1-SNAPSHOT.jar "$EC2_USER@$EC2_HOST:~/policysync.jar"
          scp -o StrictHostKeyChecking=no -i key.pem policysync.db "$EC2_USER@$EC2_HOST:~/policysync.db"

      - name: Restart app on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ec2-user
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "pkill -f 'java -jar' || true"
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "nohup java -jar policysync.jar &"